stages:
  - renovate

renovate:
  stage: renovate
  image:
    name: renovate/renovate:latest
    entrypoint: [""]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - renovate
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: "$CI_API_V4_URL"
    RENOVATE_TOKEN: "$RENOVATE_TOKEN"
    RENOVATE_REPOSITORIES: "$CI_PROJECT_PATH"
